#install-services.yml

---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: install apache in load balancers
        yum: name=httpd state=present
      - name: Start the apache and ensure it starts when we reboot
        service: name=httpd state=started enabled=yes

  - hosts: webservers
    become: true
    tasks:
      - name: Installing services apache and php in webservers
        yum:
          name:
            - httpd
            - php
          state: present
      - name: Start the apache and ensure it starts when we reboot
        service: name=httpd state=started enabled=yes